### ISSUE TITLE
https://sigma.ligma/mirrors.json is not public/accesible, causing the installer to fail

### ISSUE THREAD

**Issue by maarten99** [sp-tarkov/installer#26]
domain is actually ligma.waffle-guy or something (why not subdomain.sp-tarkov.com?), found in the installer's log

**Comment by DrakiaXYZ** [comment]
We utilize a hosting platform for file distribution outside of the main website, these are handled by individuals on the team (Waffle handles ligma.waffle/slugma.waffle and I handle spt-releases.modd.in).

The file isn't _not public_, the file doesn't exist while a new patch is being uploaded. This is currently expected behaviour
